services:
    db:
        image: postgres:17-bookworm
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./backend/.env.docker
        healthcheck:
            test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
            interval: 2s
            timeout: 10s
            retries: 5
            start_period: 30s

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        init: true
        volumes:
            - ./backend:/app
        env_file:
            - ./backend/.env.docker
        restart: unless-stopped
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        command: ["/app/start-django.sh"]

    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://backend:8000
        stdin_open: true
        tty: true
        ports:
            - "3000:80"
        depends_on:
            - backend

volumes:
    postgres_data:
    node_modules:
    static_data:
    media_data:
